name: Compile and Commit CV PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    name: compile-commit-cv-pdf
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Create output directory
        run: mkdir -p ./output
      - name: Compile CV
        run: typst compile ./cv.typ ./output/CV.pdf --font-path ./src/fonts

      - name: Generate release tag
        id: tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "tag=cv-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Create / Update Release with PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: CV â€“ ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            output/CV.pdf
          fail_on_unmatched_files: false
